export { createMetaDb } from './metaDb'
export {
  assertNotConnectionString,
  describeMetaDbUrl,
  IN_MEMORY_DB,
  META_DB_TARGET_KIND,
  metaDbFlavourOf,
  metaDbTargetOf,
} from './metaDbUrl'
export { auditWriteGapOf } from './rows'
// The one predicate for "we still hold the key that wrapped this": recovery plans and
// the effective list must not disagree about which ciphertext is unreadable.
export { providerCiphertextKeyId } from './providerCiphertexts'
// The journal's two derivations, both pure and both deliberately NOT columns: a stale
// intent read as `outcome-unknown`, and the spend rollup summed from the events.
export {
  PROVIDER_CALL_LOG_RETENTION_DEFAULT_DAYS,
  PROVIDER_CALL_LOG_RETENTION_ENV,
  providerCallLicensesAnotherAttempt,
  providerCallLogRetentionBefore,
  providerCallLogRetentionFromEnv,
  providerCallOutcomeAsRead,
  providerCallUsageTotals,
  pruneProviderCallLogRetention,
  type ProviderCallUsageTotals,
  type ProviderCallLogRetentionDays,
} from './providerCallLog'
// The half of the ability fence a host with an in-memory lifecycle journal answers
// itself. Exported so the twins' `spaceEnded` and the drivers' `phase IN (…)` cannot
// be two lists.
export { spaceLifecycleHasEnded } from './abilityLifecycle'
// What a durable ability ADDRESS is asked outside the facet that stores it: the
// package it names, and the Space that package lives in.
export { abilityPackageOfLocator, abilitySpaceOfLocator } from './abilityAddress'
export {
  ABILITY_CREATE_PHASE,
  ABILITY_TARGET_PURGED,
  PROVIDER_PERSISTENCE_ERROR,
  abilityTargetPurgedError,
  isAbilityTargetPurgedError,
  providerPersistenceError,
} from './types'
export { SqliteMetaDb } from './sqliteMetaDb'
export { PgMetaDb } from './pgMetaDb'
export type {
  AbilityCreateAccept,
  AbilityCreateCommit,
  AbilityCreateOperationRecord,
  AbilityCreatePersistence,
  AbilityCreatePhase,
  AbilityCreateTerminalResult,
  AbilityPreferenceLocator,
  AbilityPreferencesPersistence,
  AbilityPreferenceTarget,
  AgentDeltaCursorScope,
  AgentDeltaCursorsPersistence,
  AgentSessionRecord,
  AgentSessionRoleSelection,
  AgentSessionAuditEvent,
  AgentSessionAuditPersistence,
  AgentSessionAuditSummary,
  AgentSessionInferredStart,
  AgentSessionRoleSet,
  AgentSessionNamedStart,
  AgentSessionsPersistence,
  AuthPersistence,
  CiphertextWrite,
  ContextOrderEntryKind,
  ContextOrderPersistence,
  ContextOrderRecord,
  ContextSetAttachmentRecord,
  ContextSetItemRef,
  ContextSetItemsAddResult,
  ContextSetRecord,
  ContextSetsPersistence,
  ContextSetTargetKind,
  CredentialRecord,
  CredentialDeleteResult,
  CredentialMutationInput,
  CredentialMutationResult,
  CredentialMutableFields,
  CredentialReferenceValidator,
  CredentialsPersistence,
  DedupResult,
  FavoriteEntityKind,
  FavoriteRecord,
  FavoritesPersistence,
  FolderIdentityPersistence,
  FolderRecord,
  GatewayStatePersistence,
  GrantMemberToActiveSpaceResult,
  JobEnqueueInput,
  JobRecord,
  JobsPersistence,
  JobStatus,
  MemberRecord,
  MetaDb,
  OAuthAccessRecord,
  OAuthClientKind,
  OAuthClientRecord,
  OAuthCodeRecord,
  OAuthPersistence,
  OAuthRefreshRecord,
  OAuthScope,
  OneTimeTokenRecord,
  PatRecord,
  PatScope,
  ProjectRecord,
  ProjectsPersistence,
  ProjectStatus,
  ProjectRotationSecretKeyResult,
  ProviderAttachmentRecord,
  ProviderAttachmentAcceptResult,
  ProviderAttachmentLifecyclePersistence,
  ProviderAttachmentOfferResult,
  ProviderAttachmentTransitionState,
  ProviderAttachmentsPersistence,
  ProviderDisclosureBuilder,
  ProviderCallIntentInput,
  ProviderCallIntentResult,
  ProviderCallLogPersistence,
  ProviderCallLogRecord,
  ProviderCallSettleInput,
  ProviderCiphertextCarrier,
  ProviderCiphertextCounts,
  ProviderCiphertextRewrap,
  ProviderCiphertextsPersistence,
  ProviderPersistenceErrorCode,
  ProviderIdPage,
  ProviderPageInput,
  ProviderPagePosition,
  ProviderPositionPage,
  ProviderResourceRecord,
  ProviderResourcesPersistence,
  ProviderRetargetInput,
  ProviderRetargetResult,
  RetrievalAggregates,
  RetrievalHistoryQuery,
  RetrievalHit,
  RetrievalLogInput,
  RetrievalLogPersistence,
  RetrievalLogRecord,
  RetrievalQueryStat,
  RetrievalTool,
  ScopePinRecord,
  ScopePinsPersistence,
  SecretKeyringPersistence,
  SecretKeyringRecord,
  SessionRecord,
  AbilityAvailability,
  AbilityAvailabilityPersistence,
  AbilityAvailabilityRecord,
  AbilityAvailabilityRegistryNote,
  AbilityPlacementPersistence,
  OwnedRolePlacementMove,
  SpaceRecord,
  SpacesPersistence,
  UserRecord,
} from './types'
