export {
  NotariumStore,
  createNotariumStore,
  ensureNotariumResourceAuthority,
  parseNoteFile,
  serializeNoteFile,
  type CreateNotariumStoreOptions,
  type NotariumStoreOptions,
  type SearchTuning,
} from './services/notariumStore'
export {
  createLocalFsFiles,
  renameNoReplace,
  type FileClaim,
  type FileObservation,
  type FilePackagePublicationRequest,
  type FileProofTransition,
  type FilePublicationRequest,
  type FilePublicationResult,
  type FileStat,
  type FileStore,
  type FileStrictMutationReceipt,
  type FileStrictPublication,
  type FileStrictPublicationResult,
  type FileStrictStageHeader,
  type FileStrictStageRequest,
  type FileStrictStageResult,
  type FileStrictStageState,
} from './libs/files'
export {
  assertCanonicalResourceRoot,
  preflightResourceRoots,
  ResourceAdmission,
  sameFileClaim,
  SpaceResourceAuthority,
  SpaceResourceAuthorityRegistry,
  type AdmissionDiagnostic,
  type AdmissionLease,
  type AdmissionMode,
  type AdmissionRequest,
  type AdmissionScope,
  type CanonicalResourceRoot,
  type MutationReceipt,
  type ResourceAuthorityAdapter,
  type ResourceObservation,
  type ResourcePackagePublicationRequest,
  type ResourceProofTransition,
  type ResourcePublicationRequest,
  type ResourcePublicationResult,
  type ResourceRootInput,
  type ResourceStrictPublicationResult,
  type ResourceStrictStageHeader,
  type ResourceStrictStageRef,
  type ResourceStrictStageRequest,
  type ResourceStrictStageResult,
  type ResourceStrictStageState,
  type StableLinkedObservation,
  type StrictMutationReceipt,
} from './libs/resourceAuthority'
export {
  createNodeSqliteDriver,
  type NodeSqliteDriverOptions,
  type SqlDriver,
  type SqlValue,
} from './libs/sql'
export {
  createEmbedPool,
  createLocalOnnxEmbedder,
  localEmbedderAvailable,
  type Embedder,
  type EmbedKind,
  type EmbedPoolOptions,
  type LocalOnnxEmbedderOptions,
  type PoolWorker,
} from './libs/embedding'
export {
  createWholeNoteChunker,
  createHeadingChunker,
  CHUNK_CHAR_BUDGET,
  TARGET_CHUNK_CHARS,
  MAX_CHUNK_CHARS,
  OVERLAP_CHARS,
  type Chunk,
  type ChunkInput,
  type Chunker,
} from './libs/chunking'
