export {
  NotariumStore,
  createNotariumStoreComposition,
  createNotariumStore,
  ensureNotariumResourceAuthority,
  engineMountOf,
  parseNoteFile,
  serializeNoteFile,
  type CreateNotariumStoreOptions,
  type EnsureNotariumResourceAuthorityOptions,
  type EngineMount,
  type EngineMountFileAccelerators,
  type EngineMountFileCapabilities,
  type GraphAdjacencyBuildObservation,
  type NotariumStoreOptions,
  type NotariumStoreComposition,
  NotariumStoreCompositionOwner,
  type SearchTuning,
} from './services/notariumStore'
export {
  createLocalFsFiles,
  FilePackagePublicationUnavailableError,
  renameNoReplaceIfAvailable,
  type FileClaim,
  type FileClaimedRemoval,
  type FileConditionalDirectoryMove,
  type FileConditionalDirectoryMoveRequest,
  type FileConditionalDirectoryMoveResult,
  type FileConditionalMutation,
  type FileDirectoryNoReplaceMove,
  type FileEntryIdentity,
  type FileExactDirectorySpelling,
  type FileExactRead,
  type FileNoReplaceMove,
  type FileObservation,
  type FilePackagePublication,
  type FilePackagePublicationRequest,
  type FileProofTransition,
  type FilePublicationRequest,
  type FilePublicationResult,
  type FileResourceExport,
  type FileResourceObservation,
  type FileResourcePublication,
  type FileStat,
  type FileStore,
  type FileStoreAccelerators,
  type FileStoreAssembly,
  type FileStoreCapabilities,
  type FileStrictMutationReceipt,
  type FileStrictPublication,
  type FileStrictPublicationResult,
  type FileStrictStageHeader,
  type FileStrictStageRequest,
  type FileStrictStageResult,
  type FileStrictStageState,
  type FileWatch,
} from './libs/files'
export {
  assertCanonicalResourceRoot,
  type ConditionalDirectoryMoveView,
  preflightResourceRoots,
  ResourceAdmission,
  resourceAuthorityAdapterOf,
  sameFileClaim,
  SpaceResourceAuthority,
  SpaceResourceAuthorityRegistry,
  type AdmissionDiagnostic,
  type AdmissionLease,
  type AdmissionMode,
  type AdmissionRequest,
  type AdmissionScope,
  type CanonicalResourceRoot,
  type MutationReceipt,
  type PackagePublicationView,
  type ResourceAuthorityAdapter,
  type ResourceAuthorityFileCapabilities,
  type ResourceAuthorityFileView,
  type ResourceAuthorityOwner,
  type ResourceConditionalDirectoryMoveResult,
  type ResourceDirectoryMoveProof,
  type ResourceObservation,
  type ResourcePackagePublicationRequest,
  type ResourceProofTransition,
  type ResourcePublicationRequest,
  type ResourcePublicationResult,
  type ResourceRootInput,
  type ResourceStrictPublicationResult,
  type ResourceStrictStageHeader,
  type ResourceStrictStageRef,
  type ResourceStrictStageRequest,
  type ResourceStrictStageResult,
  type ResourceStrictStageState,
  type StableLinkedObservation,
  type StrictMutationReceipt,
} from './libs/resourceAuthority'
export {
  createNodeSqliteDriver,
  type NodeSqliteDriverOptions,
  type SqlDriver,
  type SqlValue,
} from './libs/sql'
export {
  createEmbedPool,
  createLocalOnnxEmbedder,
  localEmbedderAvailable,
  type Embedder,
  type EmbedKind,
  type EmbedPoolOptions,
  type LocalOnnxEmbedderOptions,
  type PoolWorker,
} from './libs/embedding'
export {
  createWholeNoteChunker,
  createHeadingChunker,
  CHUNK_CHAR_BUDGET,
  TARGET_CHUNK_CHARS,
  MAX_CHUNK_CHARS,
  OVERLAP_CHARS,
  type Chunk,
  type ChunkInput,
  type Chunker,
} from './libs/chunking'
