import type { AgentCallDecl, CaseSpec } from '../types'
import { agentSessions } from './agentSessions'

const RECURRING_INVALID_FINGERPRINT = 'seed-invalid-search-query'
const RECURRING_INVALID_ISSUE = {
  code: 'invalid_type',
  path: 'query',
  message: 'Expected string',
}

const detailedBaseCall = (call: AgentCallDecl): AgentCallDecl => {
  switch (call.ref) {
    case 'review-root-start':
      return {
        ...call,
        detailed: { project: 'main', responseFormat: 'concise', acknowledge: true },
      }
    case 'review-root-search':
      return {
        ...call,
        detailed: { query: 'migration checklist', project: 'main', class: 'user-doc' },
      }
    case 'review-root-move':
      return {
        ...call,
        tool: 'edit_note',
        domain: 'note',
        target: { ref: 'Migration findings', operation: 'replaceSection', section: 'Conclusion' },
        result: { revisions: 2 },
        detailed: {
          ref: 'Migration findings',
          operation: 'replaceSection',
          section: 'Conclusion',
        },
      }
    case 'outside-invalid':
      return {
        ...call,
        fingerprint: RECURRING_INVALID_FINGERPRINT,
        issues: RECURRING_INVALID_ISSUE,
        detailed: { project: 'main', responseFormat: 'concise' },
      }
    default:
      return call
  }
}

export const agentTelemetryDetailed: CaseSpec = {
  name: 'agent-telemetry-detailed',
  description:
    'Review matrix over the full session corpus: Compact and Detailed calls, every outcome/effect, recurring validation failures, linked retrievals and multi-revision mutations, Outside, complete/partial/archived and cross-owner episodes.',
  axes: ['agent-sessions', 'agent-audit', 'auth', 'history'],
  build: (context) => {
    const world = agentSessions.build(context)
    const calls = (world.agentCalls ?? []).map(detailedBaseCall)

    return {
      ...world,
      agentTelemetryDetailed: true,
      agentSessions: [
        ...(world.agentSessions ?? []),
        {
          ref: 'error-matrix',
          name: 'Failure outcome matrix',
          createdDaysAgo: 0.2,
          lastSeenDaysAgo: 0.006,
          calls: 3,
        },
        {
          ref: 'compact-comparison',
          name: 'Compact-only comparison',
          createdDaysAgo: 0.3,
          lastSeenDaysAgo: 0.02,
          calls: 2,
        },
        {
          ref: 'cleanup-upgrade-pending',
          name: 'Retention upgraded to human deletion',
          createdDaysAgo: 130,
          lastSeenDaysAgo: 120,
          calls: 2,
        },
        {
          ref: 'cleanup-human-complete',
          name: 'Human deletion completed',
          createdDaysAgo: 130,
          lastSeenDaysAgo: 120,
          calls: 1,
        },
      ],
      agentCalls: [
        ...calls,
        {
          ref: 'error-matrix-start',
          principal: 'pat:Codex:seed',
          agent: 'Codex',
          sessionRef: 'error-matrix',
          tool: 'start_session',
          effect: 'mutation',
          domain: 'session',
          outcome: 'success',
          daysAgo: 0.2,
          target: { taskBytes: 22 },
          result: { 'session.state': 'new' },
          detailed: { project: 'main', responseFormat: 'detailed', acknowledge: true },
        },
        {
          ref: 'error-matrix-edit',
          principal: 'pat:Codex:seed',
          agent: 'Codex',
          sessionRef: 'error-matrix',
          tool: 'edit_note',
          effect: 'mutation',
          domain: 'note',
          outcome: 'tool_error',
          reasonCode: 'stale_version',
          daysAgo: 0.008,
          target: { ref: 'Migration findings', operation: 'replaceSection' },
          result: { errorCode: 'STALE_VERSION' },
          detailed: { ref: 'Migration findings', operation: 'replaceSection', section: 'Decision' },
        },
        {
          ref: 'error-matrix-get',
          principal: 'pat:Cursor:seed',
          agent: 'Cursor',
          sessionRef: 'error-matrix',
          tool: 'get_note',
          effect: 'read',
          domain: 'retrieval',
          outcome: 'internal_error',
          reasonCode: 'interrupted',
          daysAgo: 0.006,
          target: { ref: 'Migration findings' },
          result: { errorRef: 'a1b2c3' },
          detailed: { ref: 'Migration findings', responseFormat: 'detailed' },
        },
        {
          ref: 'compact-comparison-start',
          principal: 'pat:CLI:seed',
          agent: 'CLI',
          sessionRef: 'compact-comparison',
          tool: 'start_session',
          effect: 'mutation',
          domain: 'session',
          outcome: 'success',
          daysAgo: 0.3,
          target: { taskBytes: 23 },
          result: { 'session.state': 'new' },
        },
        {
          ref: 'compact-comparison-list',
          principal: 'pat:CLI:seed',
          agent: 'CLI',
          sessionRef: 'compact-comparison',
          tool: 'list_notes',
          effect: 'read',
          domain: 'note',
          outcome: 'success',
          daysAgo: 0.02,
          target: { project: 'main', path: 'sessions', limit: 50 },
          result: { total: 8 },
        },
        {
          ref: 'review-fork-get',
          principal: 'oauth:Claude',
          agent: 'Claude',
          sessionRef: 'review-fork',
          tool: 'get_note',
          effect: 'read',
          domain: 'retrieval',
          outcome: 'success',
          daysAgo: 0.009,
          target: { ref: 'Pending for every session' },
          result: { title: 'Pending for every session' },
          detailed: { ref: 'Pending for every session', responseFormat: 'detailed' },
        },
        {
          ref: 'automatic-whoami',
          principal: 'pat:Codex:seed',
          agent: 'Codex',
          sessionRef: 'automatic',
          tool: 'whoami',
          effect: 'read',
          domain: 'identity',
          outcome: 'success',
          daysAgo: 0.49,
          result: { scope: 'write', projects: 1 },
          detailed: { session: 'explicit' },
        },
        {
          ref: 'automatic-skill',
          principal: 'pat:Codex:seed',
          agent: 'Codex',
          sessionRef: 'automatic',
          tool: 'use_skill',
          effect: 'control',
          domain: 'ability',
          outcome: 'success',
          daysAgo: 0.48,
          target: { skill: 'decision-impact' },
          result: { status: 'activated' },
          detailed: { skill: 'decision-impact', project: 'main' },
        },
        {
          ref: 'sleeping-role-denied',
          principal: 'pat:CLI:seed',
          agent: 'CLI',
          sessionRef: 'sleeping-release',
          tool: 'use_role',
          effect: 'mutation',
          domain: 'session',
          outcome: 'denied',
          reasonCode: 'ability_unavailable',
          daysAgo: 0.24,
          target: { role: 'release-captain' },
          result: { remediation: 'list_abilities' },
          detailed: { role: 'release-captain', project: 'main' },
        },
        {
          ref: 'outside-invalid-repeat-cursor',
          principal: 'pat:Cursor:seed',
          agent: 'Cursor',
          tool: 'search',
          effect: 'read',
          domain: 'retrieval',
          outcome: 'invalid_arguments',
          reasonCode: 'input_validation',
          fingerprint: RECURRING_INVALID_FINGERPRINT,
          issues: RECURRING_INVALID_ISSUE,
          daysAgo: 0.018,
          result: { issueCode: 'invalid_type' },
        },
        {
          ref: 'outside-invalid-repeat-claude',
          principal: 'oauth:Claude',
          agent: 'Claude',
          tool: 'search',
          effect: 'read',
          domain: 'retrieval',
          outcome: 'invalid_arguments',
          reasonCode: 'input_validation',
          fingerprint: RECURRING_INVALID_FINGERPRINT,
          issues: RECURRING_INVALID_ISSUE,
          daysAgo: 0.016,
          result: { issueCode: 'invalid_type' },
        },
        {
          ref: 'outside-create-denied',
          principal: 'pat:Reader:seed',
          agent: 'Reader token',
          tool: 'create_note',
          effect: 'mutation',
          domain: 'note',
          outcome: 'denied',
          reasonCode: 'insufficient_scope',
          daysAgo: 0.014,
          target: { project: 'main', title: 'Denied draft' },
          result: { requiredScope: 'write' },
          detailed: { project: 'main', title: 'Denied draft' },
        },
        {
          ref: 'review-root-list-detailed',
          principal: 'pat:CLI:seed',
          agent: 'CLI',
          sessionRef: 'review-root',
          tool: 'list_notes',
          effect: 'read',
          domain: 'note',
          outcome: 'success',
          daysAgo: 0.032,
          target: { project: 'main', path: 'sessions', limit: 50 },
          result: { total: 8 },
          detailed: { project: 'main', path: 'sessions', responseFormat: 'concise' },
        },
        {
          ref: 'detail-capture-failed',
          principal: 'pat:CLI:seed',
          agent: 'CLI',
          sessionRef: 'review-root',
          tool: 'recall',
          effect: 'read',
          domain: 'retrieval',
          outcome: 'success',
          daysAgo: 0.03,
          target: { query: 'migration decision' },
          result: { resultCount: 2 },
          detailCaptureFailed: true,
        },
        {
          ref: 'bob-private-detailed',
          owner: 'bob',
          principal: 'pat:bob:seed',
          agent: 'Bob CLI',
          sessionRef: 'bob-review',
          tool: 'search',
          effect: 'read',
          domain: 'retrieval',
          outcome: 'success',
          daysAgo: 0.04,
          target: { query: 'bob only' },
          result: { resultCount: 1 },
          detailed: { query: 'bob only', project: 'main' },
        },
        {
          ref: 'cleanup-upgrade-start',
          principal: 'pat:CLI:seed',
          agent: 'CLI',
          sessionRef: 'cleanup-upgrade-pending',
          tool: 'start_session',
          effect: 'mutation',
          domain: 'session',
          outcome: 'success',
          daysAgo: 130,
          result: { 'session.state': 'new' },
        },
        {
          ref: 'cleanup-upgrade-read',
          principal: 'pat:CLI:seed',
          agent: 'CLI',
          sessionRef: 'cleanup-upgrade-pending',
          tool: 'whoami',
          effect: 'read',
          domain: 'identity',
          outcome: 'success',
          daysAgo: 120,
        },
        {
          ref: 'cleanup-human-start',
          principal: 'pat:CLI:seed',
          agent: 'CLI',
          sessionRef: 'cleanup-human-complete',
          tool: 'start_session',
          effect: 'mutation',
          domain: 'session',
          outcome: 'success',
          daysAgo: 130,
          result: { 'session.state': 'new' },
        },
      ],
      agentCleanupMarkers: [
        {
          sessionRef: 'cleanup-upgrade-pending',
          operations: [
            { reason: 'retention', cleanup: 'pending' },
            { reason: 'human-delete', cleanup: 'pending' },
          ],
        },
        {
          sessionRef: 'cleanup-human-complete',
          operations: [{ reason: 'human-delete', cleanup: 'complete' }],
        },
      ],
      retrievals: [
        ...(world.retrievals ?? []),
        {
          principal: 'pat:CLI:seed',
          agent: 'CLI',
          sessionRef: 'cleanup-upgrade-pending',
          sessionAttach: 'declared',
          tool: 'search',
          query: 'legacy cleanup sentinel',
          daysAgo: 121,
        },
      ],
      events: world.events.map((event) =>
        event.agentAudit?.sessionRef === 'review-root'
          ? {
              ...event,
              agentAudit: { ...event.agentAudit, callRef: 'review-root-move' },
            }
          : event,
      ),
    }
  },
}
