/** `/api/*` query-param key names, compile-time bound to the wire query schemas by
 *  `schemas/queryKeysGuard.ts`. canon: docs/contract.md#wire-consts */
export const QUERY_KEY = {
  sort: 'sort',
  dir: 'dir',
  offset: 'offset',
  limit: 'limit',
  valuesLimit: 'valuesLimit',
  folder: 'folder',
  depth: 'depth',
  folders: 'folders',
  tags: 'tags',
  field: 'field',
  fieldDay: 'fieldDay',
  fieldAny: 'fieldAny',
  fieldBad: 'fieldBad',
  q: 'q',
  from: 'from',
  to: 'to',
  tz: 'tz',
  dateField: 'dateField',
  favorite: 'favorite',
  preview: 'preview',
  viewSummary: 'viewSummary',
  group: 'group',
  author: 'author',
  agent: 'agent',
  tool: 'tool',
  filter: 'filter',
  beforeAt: 'beforeAt',
  beforeId: 'beforeId',
  aggregates: 'aggregates',
  cursor: 'cursor',
  frontmatter: 'frontmatter',
  scope: 'scope',
  availability: 'availability',
} as const

export type QueryKey = (typeof QUERY_KEY)[keyof typeof QUERY_KEY]
